/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "Pin_SPI_SCLK.h"
#include "Pin_SPI_SCLK_aliases.h"
#include "Pin_SPI_MOSI.h"
#include "Pin_SPI_MOSI_aliases.h"
#include "Clock_1.h"
#include "isr_100Hz.h"
#include "Pin_SPI_SS.h"
#include "Pin_SPI_SS_aliases.h"
#include "Pin_B.h"
#include "Pin_B_aliases.h"
#include "Pin_A.h"
#include "Pin_A_aliases.h"
#include "Pin_C.h"
#include "Pin_C_aliases.h"
#include "SPIM_IntClock.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

